# Generated by Django 4.2 on 2023-04-15 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=16)),
                ('ish_vaqt', models.CharField(choices=[('08:00 | 18:00', '08:00 | 18:00'), ('18:00 | 08:00', '18:00 | 08:00')], max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Kitob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('sahifa', models.SmallIntegerField(blank=True, null=True)),
                ('janr', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Mualllif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=16)),
                ('kitob_soni', models.SmallIntegerField(blank=True, null=True)),
                ('jins', models.CharField(choices=[('Ayol', 'Ayol'), ('Erkak', 'Erkak')], max_length=50)),
                ('tirik', models.BooleanField(choices=[(True, True), (False, False)])),
                ('tugilgan_yil', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Talaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=16)),
                ('kitob_soni', models.SmallIntegerField(default=0)),
                ('kurs', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olingan_sana', models.DateTimeField()),
                ('qaytarish_sana', models.DateTimeField()),
                ('qaytgan_qaytmagan', models.BooleanField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.admin')),
                ('kitob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.kitob')),
                ('talaba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.talaba')),
            ],
        ),
        migrations.AddField(
            model_name='kitob',
            name='muallif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.mualllif'),
        ),
    ]
