# Generated by Django 4.2 on 2023-04-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='olingan_sana',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='record',
            name='qaytarish_sana',
            field=models.DateField(),
        ),
    ]
